os:
  - linux
  - osx
osx_image: xcode8.3
dist: trusty
sudo: required
language: generic
# This only needs to be run on Linux, figure out how to do that and then create
# test cases for music files
#
#before_install:
#  - sudo apt-get update
#  - sudo apt-get install -y libimage-exiftool-perl
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
script:
  - swift build -c release
  - swift test
